# Site settings
title: Justin Hall
email: jhalljhall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: jhalljhall
github_username: jhalljhall
instagram_username: jhalljhall

# Build settings
markdown: kramdown
